### ISSUE TITLE
Straight line Polygon not working

### ISSUE THREAD

**Issue by daud99** [asv-soft/asv-avalonia-map#15]
I have added two markers in Avalonia using the Demo Project. If the latitude or longitude of these markers are the same, the line between them vanishes. However, when both the latitude and longitude are different between the markers, the line is drawn perfectly.

Why is this happening? How can we fix it?

Thanks

**Comment by asv-soft-u01** [comment]
Hello!
The polygon is drawn inside of a rectangular container. When conditions described by you are met this container has basically 0 width or 0 height.

We are currently working on improving this logic so that the polygon will always be drawn fully. I will report on this issue again when this bug will be fixed.

Thanks for reporting!
Have a nice day.

Best regards,
Aleksandr.

**Comment by asv-soft-u01** [comment]
Hello!

The issue was resolved, polygons are now drawn correctly in all directions and positions!
